export const playersData = [
  {
    id: 1,
    name: "Virat Kohli",
    playingRole: "Wicketkeeper",
    credit: 10,
  },
  {
    id: 2,
    name: "Jasprit Bumrah",
    playingRole: "Bowler",
    credit: 12,
  },
  {
    id: 3,
    name: "Rohit Sharma",
    playingRole: "Batsman",
    credit: 11,
  },
  {
    id: 4,
    name: "Yuzvendra Chahal",
    playingRole: "Bowler",
    credit: 9,
  },
  {
    id: 5,
    name: "Mohammed Shami",
    playingRole: "Bowler",
    credit: 8,
  },
  {
    id: 6,
    name: "Suryakumar Yadav",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id: 7,
    name: "Prasidh Krishna",
    playingRole: "Bowler",
    credit: 7,
  },
  {
    id: 8,
    name: "Hardik Pandya",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id: 9,
    name: "Shikhar Dhawan",
    playingRole: "Batsman",
    credit: 8,
  },
  {
    id: 10,
    name: "Ravindra Jadeja",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id: 11,
    name: "Arshdeep Singh",
    playingRole: "Bowler",
    credit: 6,
  },
  {
    id: 12,
    name: "Ravichandran Ashwin",
    playingRole: "Batsman",
    credit: 1,
  },
  {
    id: 13,
    name: "Deepak Chahar",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id: 14,
    name: "Ruturaj Gaikwad",
    playingRole: "Batsman",
    credit: 8,
  },
  {
    id: 15,
    name: "Deepak Hooda",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id: 16,
    name: "Ishan Kishan",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id: 17,
    name: "Shreyas Iyer",
    playingRole: "Bowler",
    credit: 10,
  },
  {
    id: 18,
    name: "Venkatesh Iyer",
    playingRole: "Bowler",
    credit: 9,
  },
  {
    id: 19,
    name: "Dinesh Karthik",
    playingRole: "Wicketkeeper",
    credit: 11,
  },
  {
    id: 20,
    name: "Kuldeep Yadav",
    playingRole: "Bowler",
    credit: 9,
  },
  {
    id: 21,
    name: "Bhuvneshwar Kumar",
    playingRole: "Bowler",
    credit: 12,
  },
  {
    id: 22,
    name: "Mohammed Siraj",
    playingRole: "Bowler",
    credit: 10,
  },
  {
    id: 23,
    name: "Devdutt Padikkal",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id: 24,
    name: "Rishabh Pant",
    playingRole: "Wicketkeeper",
    credit: 10,
  },
  {
    id: 25,
    name: "Moeen Ali",
    playingRole: "Bowler",
    credit: 9,
  },
  {
    id: 26,
    name: "James Anderson",
    playingRole: "Bowler",
    credit: 12,
  },
  {
    id: 27,
    name: "Jonny Bairstow",
    playingRole: "Batsman",
    credit: 11,
  },
  {
    id: 28,
    name: "Sam Billings",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id: 29,
    name: "Stuart Broad",
    playingRole: "Bowler",
    credit: 9,
  },
  {
    id: 30,
    name: "Rory Burns",
    playingRole: "Bowler",
    credit: 8,
  },
  {
    id: 31,
    name: "Jos Buttler",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id: 32,
    name: "Zak Crawley",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id: 33,
    name: "Sam Curran",
    playingRole: "Bowler",
    credit: 8,
  },
  {
    id: 34,
    name: "Tom Curran",
    playingRole: "Bowler",
    credit: 7,
  },
  {
    id: 35,
    name: "Chris Jordan",
    playingRole: "Bowler",
    credit: 11,
  },
  {
    id: 36,
    name: "Jack Leach",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id: 37,
    name: "Liam Livingstone",
    playingRole: "Batsman",
    credit: 12,
  },
  {
    id: 38,
    name: "Reece Topley",
    playingRole: "Bowler",
    credit: 11,
  },
  {
    id: 39,
    name: "David Willey",
    playingRole: "Wicketkeeper",
    credit: 9,
  },
  {
    id: 40,
    name: "Joe Root",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id: 41,
    name: "Ben Stokes",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id: 42,
    name: "Pat Cummins",
    playingRole: "Bowler",
    credit: 11,
  },
  {
    id: 43,
    name: "Aaron Finch",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id: 44,
    name: "Cameron Green",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id: 45,
    name: "Josh Hazlewood",
    playingRole: "Bowler",
    credit: 9,
  },
  {
    id: 46,
    name: "Travis Head",
    playingRole: "Wicketkeeper",
    credit: 8,
  },
  {
    id: 47,
    name: "Usman Khawaja",
    playingRole: "Batsman",
    credit: 11,
  },
  {
    id: 48,
    name: "Marnus Labuschagne",
    playingRole: "Bowler",
    credit: 10,
  },
  {
    id: 49,
    name: "Nathan Lyon",
    playingRole: "Bowler",
    credit: 9,
  },
];
